version: '3.8'

services:
  backend:
    image: jaeikjeong/bimillog:backend
    container_name: bimillog-backend
    ports:
      - "8080:8080"
    networks:
      - bimillog-network
    volumes:
      - /home/ubuntu/logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:8.0.2-alpine3.21
    container_name: bimillog-redis
    ports:
      - "6379:6379"
    networks:
      - bimillog-network
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped

networks:
  bimillog-network:
    driver: bridge