server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Container name as label
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      # Container ID
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
      # Image name
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      # Add job label based on container name
      - source_labels: ['__meta_docker_container_name']
        regex: '.*(backend).*'
        target_label: 'job'
        replacement: 'bimillog-backend'
      - source_labels: ['__meta_docker_container_name']
        regex: '.*(frontend).*'
        target_label: 'job'
        replacement: 'bimillog-frontend'
      - source_labels: ['__meta_docker_container_name']
        regex: '.*(redis).*'
        target_label: 'job'
        replacement: 'redis'
      - source_labels: ['__meta_docker_container_name']
        regex: '.*(prometheus).*'
        target_label: 'job'
        replacement: 'prometheus'
      - source_labels: ['__meta_docker_container_name']
        regex: '.*(grafana).*'
        target_label: 'job'
        replacement: 'grafana'
