package jaeik.bimillog.domain.paper.entity;

/**
 * <h2>장식 타입</h2>
 * <p>
 * 다양한 장식의 종류를 정의하는 열거형
 * </p>
 *
 * @author Jaeik
 * @version 2.0.0
 */
public enum DecoType {
    // 과일
    POTATO, CARROT, CABBAGE, TOMATO, STRAWBERRY, BLUEBERRY,
    WATERMELON, PUMPKIN, APPLE, GRAPE, BANANA,

    // 이상한 장식
    GOBLIN, SLIME, ORC, DRAGON, PHOENIX,
    WEREWOLF, ZOMBIE, KRAKEN, CYCLOPS, DEVIL, ANGEL,

    // 음료
    COFFEE, MILK, WINE, SOJU, BEER, BUBBLETEA, SMOOTHIE,
    BORICHA, STRAWBERRYMILK, BANANAMILK,

    // 음식
    BREAD, BURGER, CAKE, SUSHI, PIZZA, CHICKEN, NOODLE, EGG,
    SKEWER, KIMBAP, SUNDAE, MANDU, SAMGYEOPSAL, FROZENFISH, HOTTEOK,
    COOKIE, PICKLE,

    // 동물
    CAT, DOG, RABBIT, FOX, TIGER, PANDA, LION, ELEPHANT,
    SQUIRREL, HEDGEHOG, CRANE, SPARROW, CHIPMUNK, GIRAFFE, HIPPO, POLARBEAR, BEAR,

    // 자연
    STAR, SUN, MOON, VOLCANO, CHERRY, MAPLE, BAMBOO, SUNFLOWER,
    STARLIGHT, CORAL, ROCK, WATERDROP, WAVE, RAINBOW,

    // 기타
    DOLL, BALLOON, SNOWMAN, FAIRY, BUBBLE
}

