spring:
  application:
    name: growfarm
  profiles:
    include: secret

logging:
  level:
    root: info
  file:
    name: logs/log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  threshold:
    file: error