# Spring Boot 메인 설정 파일
spring:
  application:
    name: growfarm  # 애플리케이션 이름
  profiles:
    include: prod  # secret 프로파일 포함 (환경별 설정 분리)
  datasource:
    hikari:  # HikariCP 커넥션 풀 설정
      minimum-idle: 40  # 최소 유지 커넥션 수
      maximum-pool-size: 40  # 최대 커넥션 풀 크기
      connection-timeout: 15000  # 커넥션 타임 아웃 (15초)
      max-lifetime: 1800000  # 커넥션 최대 생명주기 (30분)
      idle-timeout: 600000  # 커넥션 유휴 시간 (10분)
      leak-detection-threshold: 60000  # 커넥션 누수 감지 임계값 (60초)
  cache:  # 캐시 설정
    type: caffeine  # Caffeine 캐시 엔진 사용
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=600s  # 최대 1000개 캐시, 10분 후 만료

# 서버 설정
server:
  tomcat:
    threads:  # Tomcat 스레드 풀 설정
      max: 300  # 최대 스레드 수
      min-spare: 25  # 최소 유지 스레드 수
    accept-count: 150  # 대기열 크기
    connection-timeout: 20000  # 커넥션 타임아웃 (20초)
    uri-encoding: UTF-8  # URI 인코딩 설정
  compression:  # HTTP 응답 압축 설정
    enabled: true  # 압축 활성화
    mime-types: text/html,text/xml,text/plain,text/css,application/json  # 압축 대상 MIME 타입
    min-response-size: 1024  # 최소 압축 대상 크기 (1KB)

