spring:
  datasource:
    url: ${PROD_MYSQL_URL}
    username: ${PROD_MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        show_sql: false
        use_sql_comments: false
    open-in-view: false
    
  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT}
      password: ${REDIS_PASSWORD}
    elasticsearch:
      repository:
        enabled: true

  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    locations: ${PROD_FLYWAY_LOCATIONS}
    enabled: true

  elasticsearch:
    # AWS OpenSearch Serverless 사용
    uris: # 아직 도메인 생성 전 나중에 배포할 때 추가예정

  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    admin-key: ${KAKAO_ADMIN_KEY}
    redirect-uri: ${PROD_KAKAO_REDIRECT_URL}

# JWT 설정
jwt:
  secret: ${JWT_SECRET}

# 메시지 암호화 설정
message:
  secret: ${MESSAGE_SECRET}

# SSE URL 설정
url: ${PROD_SERVER_SSE_URL}

# 서버 설정
server:
  port: ${PROD_SERVER_PORT}