# Spring Boot 메인 설정 파일
spring:
  application:
    name: growfarm  # 애플리케이션 이름
  profiles:
    include: secret  # secret 프로파일 포함 (환경별 설정 분리)
  datasource:
    hikari:  # HikariCP 커넥션 풀 설정
      minimum-idle: 10  # 최소 유지 커넥션 수
      maximum-pool-size: 50  # 최대 커넥션 풀 크기
      leak-detection-threshold: 60000  # 커넥션 누수 감지 임계값 (60초)
  cache:  # 캐시 설정
    type: caffeine  # Caffeine 캐시 엔진 사용
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=600s  # 최대 1000개 캐시, 10분 후 만료

# 서버 설정
server:
  tomcat:
    threads:  # Tomcat 스레드 풀 설정
      max: 400  # 최대 스레드 수
      min-spare: 25  # 최소 유지 스레드 수
    accept-count: 150  # 대기열 크기
    connection-timeout: 20000  # 커넥션 타임아웃 (20초)
    uri-encoding: UTF-8  # URI 인코딩 설정
  compression:  # HTTP 응답 압축 설정
    enabled: true  # 압축 활성화
    mime-types: text/html,text/xml,text/plain,text/css,application/json  # 압축 대상 MIME 타입
    min-response-size: 1024  # 최소 압축 대상 크기 (1KB)

# 로깅 설정
logging:
  level:
    root: info  # 기본 로그 레벨
  file:
    name: logs/log  # 로그 파일 경로
  pattern:  # 로그 출력 패턴
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # 콘솔 출력 패턴
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # 파일 출력 패턴
  threshold:
    file: error  # 파일에는 error 레벨 이상만 기록



