name: CI/CD via SSM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      IMAGE_REPO: jaeikjeong/growfarm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Restore application-secret.yml
        run: |
          mkdir -p backend/src/main/resources echo "${{ secrets.SPRING_PROD_YML }}" > backend/src/main/resources/application-prod.yml

      - name: Restore .env
        run: |
          echo "${{ secrets.FRONTEND_ENV }}" > frontend/.env

      - name: Log in to Docker Hub
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build and push backend image
        run: |
          docker build -t backend ./backend
          docker tag backend:latest $IMAGE_REPO:backend
          docker push $IMAGE_REPO:backend

      - name: Build and push frontend image
        run: |
          docker build -t frontend ./frontend
          docker tag frontend:latest $IMAGE_REPO:frontend
          docker push $IMAGE_REPO:frontend

      - name: Deploy Backend via Bastion Host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.BASTION_SSH_KEY }}
          script: |
            ssh -i ~/growfarm-backend-server-key.pem -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.BACKEND_SERVER_IP }} << 'ENDSSH'
              docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
              docker pull $IMAGE_REPO:backend
              docker stop backend || true
              docker rm backend || true
              docker run -d --name backend -p 8080:8080 $IMAGE_REPO:backend
            ENDSSH

      - name: Deploy Frontend via Bastion Host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.BASTION_SSH_KEY }}
          script: |
            ssh -i ~/growfarm-frontend-server-key.pem -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.FRONTEND_SERVER_IP }} << 'ENDSSH'
              docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
              docker pull $IMAGE_REPO:frontend
              docker stop frontend || true
              docker rm frontend || true
              docker run -d --name frontend -p 3000:3000 $IMAGE_REPO:frontend
            ENDSSH


