name: CI/CD via SSM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      IMAGE_REPO: "${DOCKERHUB_USERNAME}"/growfarm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build and push backend image
        run: |
          docker build -t backend ./backend
          docker tag backend:latest $IMAGE_REPO:backend
          docker push $IMAGE_REPO:backend

      - name: Build and push frontend image
        run: |
          docker build -t frontend ./frontend
          docker tag frontend:latest $IMAGE_REPO:frontend
          docker push $IMAGE_REPO:frontend

      - name: Deploy Backend via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Name,Values=growfarm-backend-server" \
            --comment "Deploy backend container" \
            --parameters 'commands=[
              "docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}",
              "docker pull $IMAGE_REPO:backend",
              "docker stop backend || true",
              "docker rm backend || true",
              "docker run -d --name backend -p 8080:8080 $IMAGE_REPO:backend"
            ]' \
            --region ap-northeast-2

      - name: Deploy Frontend via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Name,Values=growfarm-frontend-server" \
            --comment "Deploy frontend container" \
            --parameters 'commands=[
              "docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}",
              "docker pull $IMAGE_REPO:frontend",
              "docker stop frontend || true",
              "docker rm frontend || true",
              "docker run -d --name frontend -p 3000:3000 $IMAGE_REPO:frontend"
            ]' \
            --region ap-northeast-2
